services:
  database:
    image: mysql:8.0.33
    container_name: mysql-container
    ports:
      - '3006:3306'
    environment:
      MYSQL_DATABASE: employees
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
