#
# Copyright The Asahi Shimbun Company. All rights reserved.
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.
#


services:
    # Nginx
  nginx:
    build:
      dockerfile: ./docker/env.local/nginx/Dockerfile
    volumes:
      - .:/work/backend
      - ./docker/env.local/nginx/conf.d:/etc/nginx/conf.d
      - ./storage/logs:/var/log/nginx
    networks:
      - default
    ports:
      - 8000:80
    depends_on:
      - web-app

  # PHP-Laravel
  web-app:
    build:
      context: .
      dockerfile: ./docker/env.local/php-laravel/Dockerfile
    container_name: web-app
    volumes:
      - ./:/work/backend
      - ./docker/env.local/php-laravel/.env:/work/backend/.env
      - ./docker/env.local/php-laravel/php.ini:/usr/local/etc/php/php.ini
      - ./docker/env.local/php-laravel/php-fpm.d/zzz-www.conf:/usr/local/etc/php-fpm.d/zzz-www.conf
    networks:
      - default

  # DB: MySQL
  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'accounts'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'root'
    ports:
      - 23306:3306
    networks:
      - default
    volumes:
      - ./docker/env.local/mysql/data:/docker-entrypoint-initdb.d
      - ./docker/env.local/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
